name: UltimateParticles
main: hoyinm14mc\ultimateparticles\UltimateParticles
version: Pre-alpha0.2
api:
 - 3.0.0
 - 3.0.0-ALPHA7
authors:
 - "hoyinm14mc"
 - "jasonwynn10"
description: "Particle trail plugin for PocketMine-MP mcpe server software"
load: STARTUP
permissions:
  ultimateparticles:
    default: op
    children:
      ultimateparticles.command:
        default: op
        children:
          ultimateparticles.command.ultimateparticles:
            default: op
            children:
              ultimateparticles.command.ultimateparticles.addparticle:
                default: op
                description: "Permits players to add particle to their effects"
              ultimateparticles.command.ultimateparticles.removeparticle:
                default: op
                description: "Permits players to remove particle from their effects"
              ultimateparticles.command.ultimateparticles.getparticles:
                default: true
                description: "Permits players to get a list of particles of their effect"