####### BASIC PREFERENCES #######

# Supported language(s): en
default-lang: en
# Supported effect shape(s): spiral , trail
default-shape: trail
# Supported effect type(s): particle
default-type: particle